/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/request/appeal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Создание новой заявки
         * @description Создает новую заявку с вложениями и отправляет уведомление администратору
         */
        post: operations["createAppeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список статей
         * @description Получить список статей (новости и акции)
         */
        get: operations["getArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Детали статьи
         * @description Получить одну статью по slug
         */
        get: operations["getArticleBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список баннеров */
        get: operations["getBanners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banners/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить баннер по slug или id */
        get: operations["getBanner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/request/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Создание заявки на обратный звонок
         * @description Создает новую заявку на обратный звонок и отправляет уведомление администратору
         */
        post: operations["createCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all cities */
        get: operations["getCityList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a city by ID */
        get: operations["86c851e9139604e5e1ae6138a2fc2fbf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discount-block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить данные блока скидок
         * @description Получение данных блока скидок.
         */
        get: operations["getDiscountBlock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список маркетплейсов */
        get: operations["getMarketplaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Создание нового заказа
         * @description Создаёт заказ и возвращает его номер
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить все страницы
         * @description Получить список страниц.
         */
        get: operations["getPages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить страницу по slug
         * @description Получить информацию о конкретной странице.
         */
        get: operations["getPageBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Получить офферы по slug (корзина)
         * @description Возвращает список офферов по массиву slug. Используется для корзины.
         */
        post: operations["getCartOffers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery-tomorrow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить предложения с доставкой завтра
         * @description Возвращает список офферов из блока 'Доставим завтра' (модель TomorrowDeliveryItem), учитывая город и доступность доставки.
         */
        get: operations["getDeliveryTomorrowOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Получить офферы по slug (избранное)
         * @description Возвращает список офферов по массиву slug. Используется для избранного.
         */
        post: operations["getFavoriteOffers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить хиты продаж
         * @description Возвращает список офферов, у которых установлена отметка 'хит продаж'.
         */
        get: operations["getHitOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список категорий */
        get: operations["getMenu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/category/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение списка торговых предложений по категории */
        get: operations["getOffersList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение детальной информации о торговом предложении */
        get: operations["getOfferDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список опубликованных отзывов */
        get: operations["getProductReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Поиск товарных предложений
         * @description Выполняет полнотекстовый поиск по заголовку товарных предложений с пагинацией и загрузкой связанных сущностей.
         */
        get: operations["searchOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/promo-code/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверка существования промокода */
        get: operations["getPromoCodeCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publications/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список категорий публикаций */
        get: operations["getPublicationCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publications/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить категорию публикации по ID */
        get: operations["getPublicationCategoryById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список публикаций */
        get: operations["getPublications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить публикацию по ID */
        get: operations["getPublicationById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/running-lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить список всех бегущих строк
         * @description Возвращает список всех бегущих строк.
         */
        get: operations["getRunningLinesList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/running-lines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить конкретную бегущую строку по ID
         * @description Возвращает одну бегущую строку по её идентификатору.
         */
        get: operations["getRunningLineById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/site-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить настройки сайта */
        get: operations["getSiteSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sliders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список слайдеров */
        get: operations["getSliders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/request/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подписка на рассылку
         * @description Создает новую подписку на рассылку и отправляет письмо с промокодом на скидку
         */
        post: operations["createSubscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список тегов */
        get: operations["getTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить тег по slug */
        get: operations["getTag"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Article
         * @description Ресурс статьи
         */
        ArticleResource: {
            /** @example 1 */
            id?: number;
            /** @example Новость дня */
            name?: string;
            /** @example Важное обновление */
            title?: string;
            /** @example vazhnoe-obnovlenie */
            slug?: string;
            /** @example https://example.com/image.jpg */
            image?: string | null;
            /** @example Краткое описание статьи */
            description?: string;
            /**
             * @example news
             * @enum {string}
             */
            type?: "sale" | "news";
            /** @example https://example.com/read-more */
            button_url?: string | null;
            /** @example true */
            is_published?: boolean;
            /** @example 1 */
            order?: number;
            /**
             * Format: date-time
             * @example 2025-02-25T12:34:56Z
             */
            date?: string;
            /**
             * Format: date-time
             * @example 2025-02-25T12:34:56Z
             */
            created_at?: string;
            /**
             * Format: date-time
             * @example 2025-02-26T08:12:30Z
             */
            updated_at?: string;
        };
        /**
         * Баннер
         * @description Ресурс баннера
         */
        BannerResource: {
            /** @description Идентификатор баннера */
            id?: number;
            /** @description Название баннера */
            name?: string;
            /** @description Подзаголовок баннера */
            sub_name?: string;
            /** @description ЧПУ баннера */
            slug?: string;
            /** @description Цвет фона баннера */
            color_bg?: string;
            /** @description Цвет текста баннера */
            color_text?: string;
            /** @description Изображение фона баннера */
            background_image?: string;
            /** @description Изображение переднего плана баннера */
            front_image?: string;
            /** @description Тип баннера */
            type?: string;
            /**
             * Format: date-time
             * @description Дата и время начала публикации
             */
            publish_start?: string;
            /**
             * Format: date-time
             * @description Дата и время окончания публикации
             */
            publish_end?: string;
            /** @description Статус публикации */
            is_published?: boolean;
            /** @description Список тегов баннера */
            tags?: {
                /** @description Идентификатор тега */
                id?: number;
                /** @description Название тега */
                title?: string;
                /** @description ЧПУ тега */
                slug?: string;
            }[];
        };
        City: {
            id?: number;
            name?: string;
            title_delivery?: string;
            description_delivery?: string;
            address?: string;
            longitude?: string;
            latitude?: string;
            delivery_time?: string;
            delivery_in_city?: string;
            delivery_outside_city?: string;
            loads_up_lifting?: string;
            loads_up_stairs?: string;
        };
        /**
         * DiscountBlock
         * @description Данные блока скидок
         */
        DiscountBlockResource: {
            /** @example Супер скидки */
            title?: string;
            /** @example Купить сейчас */
            button_text?: string;
            /** @example https://example.com */
            button_link?: string;
            /**
             * @example [
             *       "image1.jpg",
             *       "image2.jpg"
             *     ]
             */
            slider_images?: string[];
            /** @example #FFFFFF */
            background_color?: string;
            /** @example #000000 */
            title_color?: string;
            /** @example background.jpg */
            background_image?: string;
        };
        /**
         * Маркетплейсы
         * @description Ресурс маркетплейсов
         */
        MarketplaceResource: {
            /** @description Идентификатор маркетплейса */
            id?: number;
            /** @description Название маркетплейса */
            name?: string;
            /** @description ЧПУ маркетплейса */
            slug?: string;
            /** @description URL иконки */
            icon?: string;
            /** @description оценка */
            rating?: string;
        };
        Page: {
            /** @example 1 */
            id?: number;
            /** @example Название страницы */
            name?: string;
            /** @example Заголовок страницы */
            title?: string;
            /** @example example-page */
            slug?: string;
            /** @example 100 */
            order?: number;
            /** @example true */
            is_published?: boolean;
            /**
             * Format: html
             * @example <p>Описание страницы</p>
             */
            description?: string;
            /**
             * Format: url
             * @example https://example.com/images/large.jpg
             */
            image_large?: string | null;
            /**
             * Format: url
             * @example https://example.com/images/small.jpg
             */
            image_small?: string | null;
            /** @description Массив контента, у каждого свой тип */
            content?: {
                /** @example table */
                type?: string;
                /** @example Заголовок блока */
                title?: string;
                /**
                 * Format: html
                 * @example <p>Текст блока</p>
                 */
                content?: string;
                /**
                 * Format: url
                 * @example https://example.com/images/content-large.jpg
                 */
                image_large?: string | null;
                /**
                 * Format: url
                 * @example https://example.com/images/content-small.jpg
                 */
                image_small?: string | null;
            }[];
        };
        /** Категория */
        ProductCategoryResource: {
            /**
             * @description Идентификатор категории
             * @example 1
             */
            id?: number;
            /**
             * @description Название категории
             * @example Смартфоны
             */
            name?: string;
            /**
             * @description Название категории для меню
             * @example Смартфоны
             */
            menu_title?: string;
            /**
             * @description ЧПУ категории
             * @example smartfony
             */
            slug?: string;
            /**
             * @description Полный ЧПУ категории
             * @example elektronika/smartfony
             */
            full_slug?: string;
            /**
             * Format: url
             * @description Изображение категории
             * @example https://example.com/images/category.jpg
             */
            image?: string | null;
            /**
             * @description Иконка категории
             * @example smartphone
             */
            icon?: string | null;
            /**
             * @description Статус публикации
             * @example true
             */
            is_published?: boolean;
            /**
             * @description Порядок сортировки категории
             * @example 1
             */
            order?: number;
            /**
             * @description Кол-во товаров в категории
             * @example 1
             */
            count?: number;
            /** @description Баннеры для категории */
            banners?: components["schemas"]["BannerResource"][];
            /**
             * @description Левая граница (nested set)
             * @example 1
             */
            _lft?: number;
            /**
             * @description Правая граница (nested set)
             * @example 2
             */
            _rgt?: number;
            /** @description Подкатегории */
            children?: components["schemas"]["ProductCategoryResource"][];
        };
        /**
         * Детальная информация о торговом предложении
         * @description Ресурс детального представления торгового предложения
         */
        OfferDetailResource: {
            /** @description Идентификатор торгового предложения */
            id?: number;
            /** @description Артикул торгового предложения */
            article?: string;
            /** @description Название товара (title из модели Product) */
            name?: string;
            /** @description Полное название товара с предложением */
            sub_name?: string;
            /** @description Артикул (используется как slug) */
            slug?: string;
            /** @description Slug категории товара */
            category_slug?: string;
            /** @description Главное изображение предложения */
            image?: string | null;
            /** @description Цены предложения */
            cost?: {
                /**
                 * Format: float
                 * @description Текущая цена
                 */
                price?: number | null;
                /**
                 * Format: float
                 * @description Старая цена
                 */
                old_price?: number | null;
                /** @description Скидка в процентах */
                discount?: string | null;
            };
            /** @description Количество в наличии */
            in_stock?: number;
            /** @description Флаг бестселлера */
            is_bestseller?: boolean;
            /** @description Флаг комплектного предложения */
            is_complect?: boolean;
            /** @description Срок доставки в в текстовом формате */
            days_for_delivery?: string;
            /** @description Галерея изображений */
            gallery?: string[];
            /** @description Список тегов */
            tag_list?: components["schemas"]["TagResource"][];
            /** @description Характеристики товара */
            parameters?: {
                /** @description ID характеристики */
                property_id?: number;
                /** @description Название характеристики */
                title?: string;
                /** @description Значение характеристики */
                value?: string;
                /** @description Единица измерения */
                measure?: string | null;
            }[];
            /** @description Сгруппированные сопутствующие товары */
            products_related?: {
                /** @description Название группы */
                title_group?: string;
                products?: components["schemas"]["OfferListResource"][];
                /** @description Slug основной категории товара */
                product_category_slug?: string;
                /** @description Список slug подкатегорий предложения */
                offer_category_slug?: string[];
            }[];
            /** @description Отзывы к товару */
            reviews?: components["schemas"]["ReviewResource"][];
            /** @description Описание товара в виде секций */
            description?: {
                /** @description Заголовок секции */
                title?: string | null;
                /** @description Текст секции */
                text?: string | null;
                /** @description Изображение секции */
                image?: string | null;
            }[];
            /** @description Изображения с габаритами */
            blueprints?: string[];
            /** @description Похожие товары */
            similar?: components["schemas"]["OfferListResource"][];
            /** @description Другие варианты этого предложения */
            variants?: {
                /** @description Идентификатор варианта */
                id?: number;
                /** @description Артикул варианта */
                article?: string;
                /** @description Slug категории продукта */
                product_slug?: string;
                /** @description Является ли данный вариант активным */
                is_active?: boolean;
                /** @description Порядок сортировки варианта */
                order?: number;
                /** @description Цены варианта */
                cost?: {
                    /**
                     * Format: float
                     * @description Текущая цена
                     */
                    price?: number | null;
                    /**
                     * Format: float
                     * @description Старая цена
                     */
                    old_price?: number | null;
                    /**
                     * Format: float
                     * @description Размер скидки
                     */
                    discount?: number | null;
                };
                /** @description Групповые параметры варианта */
                group_params?: {
                    title?: string;
                    value?: string;
                    measure?: string | null;
                }[];
                /** @description Списковые параметры варианта */
                list_params?: {
                    title?: string;
                    value?: string;
                    preview?: string | null;
                    measure?: string | null;
                }[];
            }[];
        };
        /**
         * Список торговых предложений
         * @description Ресурс торгового предложения в списке
         */
        OfferListResource: {
            /** @description Идентификатор торгового предложения */
            id?: number;
            /** @description Артикул торгового предложения */
            article?: string;
            /** @description Название товара (title из модели Product) */
            name?: string;
            /** @description Полное название товара с предложением */
            sub_name?: string;
            /** @description Артикул (используется как slug) */
            slug?: string;
            /** @description Slug категории товара */
            category_slug?: string;
            /** @description Главное изображение предложения */
            image?: string | null;
            /** @description Цены предложения */
            cost?: {
                /**
                 * Format: float
                 * @description Текущая цена
                 */
                price?: number | null;
                /**
                 * Format: float
                 * @description Старая цена
                 */
                old_price?: number | null;
                /** @description Скидка в процентах */
                discount?: number | null;
            };
            /** @description Текс о днях доставки */
            days_for_delivery?: string;
            /** @description Галерея изображений */
            gallery?: string[];
            /** @description Групповые параметры торгового предложения */
            group_params?: {
                /** @description Название параметра */
                title?: string;
                /** @description Значение параметра */
                value?: string;
                /** @description Единица измерения */
                measure?: string | null;
                /** @description Тип параметра */
                type?: string;
            }[];
            /** @description Параметры торгового предложения со справочными значениями */
            list_params?: {
                /** @description Название параметра */
                title?: string;
                /** @description Название выбранного значения из справочника */
                value?: string;
                /** @description Превью изображения значения */
                preview?: string | null;
                /** @description Единица измерения */
                measure?: string | null;
                /** @description Тип параметра (должен быть 'list') */
                type?: string;
            }[];
            /** @description Список slug подкатегорий торгового предложения */
            offer_category_slug?: string[];
        };
        /**
         * ReviewResource
         * @description Ресурс отзыва о товаре
         */
        ReviewResource: {
            /**
             * @description ID отзыва
             * @example 1
             */
            id?: number;
            /** @description Список связанных товаров */
            products?: {
                /**
                 * @description ID товара
                 * @example 10
                 */
                id?: number;
            }[];
            /**
             * Format: url
             * @description URL изображения отзыва
             * @example https://example.com/images/review.jpg
             */
            image?: string | null;
        };
        /**
         * Промокод
         * @description Ресурс Промокодов
         */
        PromoCode: {
            /** @description Уникальный код промокода */
            code?: string;
            /** @description Сумма, на которую действует промокод */
            sum?: string;
        };
        PublicationsCategoryResource: {
            /**
             * @description Идентификатор категории
             * @example 1
             */
            id?: number;
            /**
             * @description Название категории
             * @example Идеи для комнат
             */
            title?: string;
            /**
             * @description Описание категории
             * @example <p>Мы собрали нашу похожую по стилю мебель в готовые решения для ваших комнат</p>
             */
            description?: string;
            /** @description Публикации в категории */
            items?: components["schemas"]["PublicationResource"][];
        };
        /** Публикация */
        PublicationResource: {
            /** @description Идентификатор публикации */
            id?: number;
            /** @description Заголовок публикации */
            title?: string;
            /** @description ЧПУ публикации */
            slug?: string;
            /** @description Изображение публикации */
            image?: string;
            category?: components["schemas"]["PublicationsCategoryResource"];
        };
        /**
         * Бегущая строка
         * @description Структура данных для ресурса бегущей строки
         */
        RunningLineResource: {
            /**
             * @description Идентификатор записи
             * @example 1
             */
            id?: number;
            /**
             * @description Название строки
             * @example Тестовая строка
             */
            name?: string;
            /**
             * @description Текст строки
             * @example Это тест
             */
            text?: string;
            /**
             * @description URL изображения
             * @example http://your-app.test/storage/running_lines/image.jpg
             */
            image?: string | null;
            /**
             * @description Ссылка
             * @example https://example.com
             */
            link?: string | null;
            /**
             * @description Активна ли строка
             * @example true
             */
            is_active?: boolean;
            /**
             * Format: date-time
             * @description Дата создания
             * @example 2025-02-26 12:00:00
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description Дата обновления
             * @example 2025-02-26 12:00:00
             */
            updated_at?: string;
        };
        /** Ресурс сео (мета тегов) */
        SeoResource: {
            /**
             * Заголовок
             * @example Заголовок
             */
            title?: string | null;
            /**
             * Описание
             * @example Описание
             */
            description?: string | null;
        };
        SiteSettingsResource: {
            data?: {
                seo?: {
                    title?: string;
                    description?: string;
                };
                /** @example 1 */
                city_id?: number | null;
                /** @example +7 812 223-50-59 */
                phone_number?: string | null;
                /** @example example@example.com */
                email?: string | null;
                /** @example г. Москва, ул. Ленина, д. 10, офис 25 */
                legal_address?: string | null;
                /** @example Пн-Пт: 9:00 - 18:00 */
                working_hours?: string | null;
                /** @example Пн-Пт: 10:00 - 20:00 */
                delivery_hours?: string | null;
                social_networks?: {
                    /** @example ВКонтакте */
                    name?: string;
                    /**
                     * Format: uri
                     * @example http://example.com/storage/path/to/icon.svg
                     */
                    icon?: string;
                    /**
                     * Format: uri
                     * @example https://vk.com
                     */
                    link?: string;
                }[] | null;
                /**
                 * Format: url
                 * @example http://example.com/storage/path/to/privacy_policy.pdf
                 */
                privacy_policy?: string | null;
                /**
                 * Format: url
                 * @example http://example.com/storage/path/to/offer.pdf
                 */
                offer?: string | null;
                /** @example <p>Описание главной страницы</p> */
                home_description_html?: string | null;
                /**
                 * Format: url
                 * @example http://example.com/storage/path/to/image.jpg
                 */
                home_description_image?: string | null;
                /** @example 1 */
                running_line_id?: number | null;
                /** @example 1 */
                idea_id?: number | null;
            };
        };
        /**
         * Слайдер
         * @description Ресурс слайдера
         */
        SliderResource: {
            /** @description Идентификатор слайдера */
            id?: number;
            /** @description Заголовок слайдера */
            title?: string;
            /** @description Текст над заголовком слайда */
            pretitle?: string;
            /** @description Подзаголовок слайдера */
            subtitle?: string;
            /** @description ЧПУ слайдера */
            slug?: string;
            /** @description Текст кнопки слайдера */
            button_text?: string;
            /** @description Цвет фона слайдера */
            background_color?: string;
            /** @description Цвет текста слайдера */
            text_color?: string;
            /** @description Изображение фона слайдера */
            background_image?: string;
            /** @description Изображение продукта */
            product_image?: string;
            /** @description Порядок сортировки слайдера */
            order?: number;
            /**
             * Format: date-time
             * @description Начало акции
             */
            promotion_start?: string;
            /**
             * Format: date-time
             * @description Окончание акции
             */
            promotion_end?: string;
        };
        /**
         * TagResource
         * @description Ресурс тега
         */
        TagResource: {
            /**
             * @description Идентификатор тега
             * @example 1
             */
            id?: number;
            /**
             * @description Название тега
             * @example Новинки
             */
            title?: string;
            /**
             * @description ЧПУ тега
             * @example novinki
             */
            slug?: string;
            /**
             * @description Цвет фона тега
             * @example #FF5733
             */
            background_color?: string;
            /**
             * Format: url
             * @description URL изображения тега
             * @example https://example.com/images/tag.jpg
             */
            image_url?: string;
            /**
             * Format: url
             * @description Ссылка на страницу тега
             * @example https://example.com/tags/novinki
             */
            link?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createAppeal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Данные для создания заявки */
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * @description Имя
                     * @example Иван
                     */
                    first_name: string;
                    /**
                     * @description Фамилия
                     * @example Иванов
                     */
                    last_name: string;
                    /**
                     * @description Email (необязательно)
                     * @example ivan@example.com
                     */
                    email?: string;
                    /**
                     * @description Телефон
                     * @example +79991234567
                     */
                    phone: string;
                    /**
                     * @description Сообщение
                     * @example Описание проблемы
                     */
                    message?: string;
                    photo_product?: string[];
                    photo_defect?: string[];
                    video?: string[];
                    photo_packaging?: string[];
                };
            };
        };
        responses: {
            /** @description Заявка успешно создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Заявка успешно отправлена */
                        message?: string;
                    };
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Ошибка валидации */
                        message?: string;
                        /**
                         * @example {
                         *       "first_name": [
                         *         "The first name field is required."
                         *       ],
                         *       "phone": [
                         *         "The phone format is invalid."
                         *       ]
                         *     }
                         */
                        errors?: Record<string, never>;
                    };
                };
            };
        };
    };
    getArticles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ArticleResource"][];
                    };
                };
            };
        };
    };
    getArticleBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug статьи */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ArticleResource"];
                        seo?: components["schemas"]["SeoResource"];
                    };
                };
            };
            /** @description Статья не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBanners: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список баннеров */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["BannerResource"][];
                    };
                };
            };
        };
    };
    getBanner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ЧПУ баннера или его ID */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Детали баннера */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["BannerResource"];
                    };
                };
            };
            /** @description Баннер не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Баннер не найден */
                        error?: string;
                    };
                };
            };
        };
    };
    createCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Имя пользователя */
                    name?: string;
                    /** @description Номер телефона */
                    phone?: string;
                };
            };
        };
        responses: {
            /** @description Заявка успешно создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Заявка успешно отправлена */
                        message?: string;
                    };
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The given data was invalid. */
                        message?: string;
                        /**
                         * @example {
                         *       "name": [
                         *         "The name field is required."
                         *       ]
                         *     }
                         */
                        errors?: Record<string, never>;
                    };
                };
            };
        };
    };
    getCityList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["City"][];
                };
            };
        };
    };
    "86c851e9139604e5e1ae6138a2fc2fbf": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["City"];
                };
            };
        };
    };
    getDiscountBlock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["DiscountBlockResource"][];
                    };
                };
            };
        };
    };
    getMarketplaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список маркетплейсов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["TagResource"][];
                    };
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header: {
                /** @description ID города */
                "X-City-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    request_offers: {
                        /** @example ABC123 */
                        slug: string;
                        /** @example 2 */
                        count: number;
                        /** @example 2000 */
                        price?: number;
                        /** @example 2000 */
                        price_not_discount?: number;
                        /** @example 2000 */
                        discount?: number;
                    }[];
                    /** @example 2700 */
                    request_sum?: number | null;
                    /** @example 3000 */
                    request_sum_not_discount: number;
                    /** @example 300 */
                    request_discount: number;
                    /** @example SPRING2025 */
                    request_promo_code?: string | null;
                    /** @example Иван */
                    name: string;
                    /** @example Иванов */
                    surname?: string | null;
                    /**
                     * Format: email
                     * @example ivan@example.com
                     */
                    email?: string;
                    /** @example +79991234567 */
                    phone: string;
                    /** @example Москва */
                    city: string;
                    /** @example Ленина */
                    street: string;
                    /** @example 10 */
                    house: string;
                    /** @example 25 */
                    apartment?: string | null;
                    /** @example 3 */
                    floor?: number | null;
                    /** @example true */
                    is_lifting: boolean;
                    /** @example Позвонить за 30 минут */
                    comment?: string | null;
                    /** @example split */
                    payment_method?: string | null;
                };
            };
        };
        responses: {
            /** @description Заказ успешно создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 000123 */
                        order_id?: string;
                    };
                };
            };
            /** @description Некоторые товары недоступны для заказа */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Некоторые из выбранных товаров недоступны. */
                        message?: string;
                        /**
                         * @example [
                         *       "ABC123",
                         *       "XYZ456"
                         *     ]
                         */
                        unavailable_slugs?: string[];
                    };
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        errors?: {
                            /**
                             * @example [
                             *       "Поле обязательно для заполнения."
                             *     ]
                             */
                            request_offers?: string[];
                            /**
                             * @example [
                             *       "Поле обязательно для заполнения."
                             *     ]
                             */
                            name?: string[];
                            /**
                             * @example [
                             *       "Поле обязательно для заполнения."
                             *     ]
                             */
                            phone?: string[];
                        };
                    };
                };
            };
        };
    };
    getPages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"][];
                };
            };
        };
    };
    getPageBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Page"];
                        seo?: components["schemas"]["SeoResource"];
                    };
                };
            };
            /** @description Страница не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCartOffers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Массив slug офферов
                     * @example [
                     *       "slug-1",
                     *       "slug-2"
                     *     ]
                     */
                    slugs: string[];
                };
            };
        };
        responses: {
            /** @description Список офферов, найденных по slug */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["OfferListResource"][];
                    };
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDeliveryTomorrowOffers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список офферов с отметкой 'Доставим завтра' */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["OfferListResource"][];
                    };
                };
            };
        };
    };
    getFavoriteOffers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Массив slug офферов
                     * @example [
                     *       "slug-1",
                     *       "slug-2"
                     *     ]
                     */
                    slugs: string[];
                };
            };
        };
        responses: {
            /** @description Список офферов, найденных по slug */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["OfferListResource"][];
                    };
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHitOffers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список офферов с флагом 'хит продаж' */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["OfferListResource"][];
                    };
                };
            };
        };
    };
    getMenu: {
        parameters: {
            query?: never;
            header?: {
                /** @description ID города для фильтрации категорий */
                "X-City-Id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Получить меню магазина */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ProductCategoryResource"][];
                    };
                };
            };
        };
    };
    getOffersList: {
        parameters: {
            query?: {
                /** @description Количество элементов на страницу (по умолчанию 12) */
                perPage?: number;
                /** @description Сортировка: new - новые, cheaper - дешевле, expensive - дороже */
                sort?: "new" | "cheaper" | "expensive";
            };
            header?: {
                /** @description Идентификатор города для фильтрации цен */
                "X-City-Id"?: number;
            };
            path: {
                /** @description Slug категории */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список торговых предложений с пагинацией */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["OfferListResource"][];
                        links?: {
                            /** @description Ссылка на первую страницу */
                            first?: string;
                            /** @description Ссылка на последнюю страницу */
                            last?: string;
                            /** @description Ссылка на предыдущую страницу */
                            prev?: string | null;
                            /** @description Ссылка на следующую страницу */
                            next?: string | null;
                        };
                        meta?: {
                            /** @description Текущая страница */
                            current_page?: number;
                            /** @description Номер первого элемента на странице */
                            from?: number;
                            /** @description Общее количество страниц */
                            last_page?: number;
                            /** @description Базовый URL запроса */
                            path?: string;
                            /** @description Количество элементов на страницу */
                            per_page?: number;
                            /** @description Номер последнего элемента на странице */
                            to?: number;
                            /** @description Общее количество элементов */
                            total?: number;
                        };
                        seo?: components["schemas"]["SeoResource"];
                        /** @description Текст описания категории */
                        category_description_text?: string | null;
                        /**
                         * Format: url
                         * @description Изображение описания категории
                         */
                        category_description_image?: string | null;
                    };
                };
            };
            /** @description Категория не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOfferDetail: {
        parameters: {
            query?: never;
            header?: {
                /** @description Идентификатор города для фильтрации цен */
                "X-City-Id"?: number;
            };
            path: {
                /** @description Артикул торгового предложения */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Детальная информация о торговом предложении */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["OfferDetailResource"];
                    };
                };
            };
            /** @description Торговое предложение не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProductReviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список отзывов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ReviewResource"][];
                    };
                };
            };
        };
    };
    searchOffers: {
        parameters: {
            query?: {
                /** @description Поисковый запрос */
                search?: string;
                /** @description Количество элементов на страницу */
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ. Список товарных предложений. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["OfferListResource"][];
                        links?: Record<string, never>;
                        meta?: Record<string, never>;
                    };
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPromoCodeCheck: {
        parameters: {
            query: {
                /** @description Промокод */
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Промокод найден */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromoCode"];
                };
            };
            /** @description Промокод не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Промокод не найден */
                        message?: string;
                    };
                };
            };
        };
    };
    getPublicationCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список категорий */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PublicationsCategoryResource"][];
                    };
                };
            };
        };
    };
    getPublicationCategoryById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID категории */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Данные категории */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PublicationsCategoryResource"];
                        seo?: components["schemas"]["SeoResource"];
                    };
                };
            };
            /** @description Категория не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Категория не найдена */
                        error?: string;
                    };
                };
            };
        };
    };
    getPublications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список публикаций */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PublicationResource"][];
                        /** @description Навигация по страницам */
                        links?: Record<string, never>;
                        /** @description Метаданные пагинации */
                        meta?: Record<string, never>;
                    };
                };
            };
        };
    };
    getPublicationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID публикации */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Данные публикации */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PublicationResource"];
                        seo?: components["schemas"]["SeoResource"];
                    };
                };
            };
            /** @description Публикация не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Публикация не найдена */
                        error?: string;
                    };
                };
            };
        };
    };
    getRunningLinesList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешная операция */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["RunningLineResource"][];
                    };
                };
            };
            /** @description Внутренняя ошибка сервера */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Ошибка сервера */
                        message?: string;
                    };
                };
            };
        };
    };
    getRunningLineById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор бегущей строки для получения */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешная операция */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["RunningLineResource"][];
                    };
                };
            };
            /** @description Бегущая строка не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Не найдено */
                        message?: string;
                    };
                };
            };
            /** @description Внутренняя ошибка сервера */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Ошибка сервера */
                        message?: string;
                    };
                };
            };
        };
    };
    getSiteSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteSettingsResource"];
                };
            };
            /** @description Ошибка сервера */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSliders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список слайдеров */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["SliderResource"][];
                    };
                };
            };
        };
    };
    createSubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @description Email пользователя
                     */
                    email?: string;
                };
            };
        };
        responses: {
            /** @description Подписка успешно создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Вы успешно подписались на рассылку! */
                        message?: string;
                    };
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Ошибка валидации */
                        message?: string;
                        /**
                         * @example {
                         *       "email": [
                         *         "Вы уже подписаны на рассылку."
                         *       ]
                         *     }
                         */
                        errors?: Record<string, never>;
                    };
                };
            };
        };
    };
    getTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список тегов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["TagResource"][];
                    };
                };
            };
        };
    };
    getTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ЧПУ тега */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Детали тега */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["TagResource"];
                    };
                };
            };
            /** @description Тег не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Тег не найден */
                        error?: string;
                    };
                };
            };
        };
    };
}
