//libs
import clsx from "clsx";

//styles
import "@/core/styles/globals.scss";

//types
import type { Metadata } from "next";

//query provider
import { QueryProvider } from "@/core/providers/QueryProvider";

//fonts
import { CygreFont, VelaSansFont } from "./_fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={clsx(CygreFont.variable, VelaSansFont.variable)}>
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
