import type { Metadata } from "next";
import "../styles/globals.scss";
import { QueryProvider } from "@/providers/QueryProvider";
import { CygreFont, VelaSansFont } from './_fonts';
import clsx from 'clsx';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={clsx(CygreFont.variable, VelaSansFont.variable)}>
      <body >
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
